# Generated by Django 6.0.3 on 2026-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='chatbot_diagnosis',
            field=models.TextField(blank=True),
        ),
    ]
