# Generated by Django 6.0.3 on 2026-04-14 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctorleave_status'),
        ('medical_records', '0002_consultation_chatbot_diagnosis'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='administrative_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='annex_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinical_examination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='complementary_exams',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='consultation_motive',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='current_illness_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnostic_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medical_background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_full_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_management',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MedicalDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('analysis', 'Analysis'), ('imaging', 'Imaging'), ('document', 'Document'), ('other', 'Other')], default='document', max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('requested_items', models.JSONField(blank=True, default=list)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='doctors.doctorprofile')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('analysis_report', 'Analysis Report'), ('imaging_result', 'Imaging Result'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/%d/')),
                ('review_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_medical_documents', to='doctors.doctorprofile')),
                ('uploaded_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_documents', to='doctors.doctorprofile')),
                ('uploaded_by_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_documents', to='patients.patientprofile')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='medical_records.medicaldocumentrequest')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
