# Generated by Django 6.0.7 on 2026-04-15

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_medicalrecord_longitudinal_metrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=180)),
                ('details', models.TextField(blank=True)),
                ('scheduled_start', models.DateTimeField()),
                ('expected_duration_minutes', models.PositiveIntegerField(default=120)),
                ('expected_end_at', models.DateTimeField()),
                ('release_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='medical_records.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='doctors.doctorprofile')),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_operations', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='medical_records.medicalrecord')),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doctoroperation',
            index=models.Index(fields=['doctor', 'scheduled_start'], name='medical_reco_doctor__568ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoroperation',
            index=models.Index(fields=['doctor', 'release_at'], name='medical_reco_doctor__6ddc48_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctoroperation',
            constraint=models.CheckConstraint(condition=Q(expected_duration_minutes__gt=0), name='doctor_operation_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='doctoroperation',
            constraint=models.CheckConstraint(condition=Q(release_at__gte=models.F('scheduled_start')), name='doctor_operation_release_after_start'),
        ),
    ]
