# Generated by Django 6.0.3 on 2026-04-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(choices=[('cardiology', 'Departement de cardiologie'), ('respiratory', 'Departement des maladies respiratoires'), ('neurology', 'Departement de neurologie'), ('gastroenterology', 'Departement de gastroenterologie'), ('dermatology', 'Departement de dermatologie'), ('endocrinology', "Departement d'endocrinologie"), ('general_medicine', 'Departement de medecine generale')], default='general_medicine', max_length=40),
        ),
    ]
