# Generated by Django 6.0.3 on 2026-04-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status_appointmentadvanceoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_staff_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
