# Generated by Django 6.0.3 on 2026-04-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_existing_leave_status(apps, schema_editor):
    DoctorLeave = apps.get_model('doctors', 'DoctorLeave')
    DoctorLeave.objects.filter(is_active=True).update(status='approved')
    DoctorLeave.objects.filter(is_active=False).update(status='rejected')


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorleave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_doctor_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(set_existing_leave_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='doctorleave',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
