# Generated by Django 6.0.3 on 2026-04-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_backfill_missing_doctor_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorleave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
