# Generated by Django 6.0.3 on 2026-04-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status_appointmentadvanceoffer'),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsession',
            name='awaiting_appointment_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='booked_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_session', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='chatbotsession',
            name='latest_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
